### ISSUE TITLE
jugadorInicial puede hacerse con composición

### ISSUE THREAD

**Issue by natoszme** [dlopezjoffreutn/PDP_LopezJoffre_Dolores#1]
https://github.com/dlopezjoffreutn/PDP_LopezJoffre_Dolores/blob/61130acfe2f5b393d069b190ad540da365a6ebdb/tp-monopoly/src/Lib.hs#L41

Usando `cambiarDinero` y `cambiarPropiedad` (que en realidad, son `propiedades` :) )

**Comment by dlopezjoffreutn** [comment]
es verdad, es verdad

**Comment by dlopezjoffreutn** [comment]
fix 44c8492
