### ISSUE TITLE
Estaría bueno que juegoFinal devuelva al jugador después de haber jugado

### ISSUE THREAD

**Issue by natoszme** [dlopezjoffreutn/PDP_LopezJoffre_Dolores#6]
https://github.com/dlopezjoffreutn/PDP_LopezJoffre_Dolores/blob/61130acfe2f5b393d069b190ad540da365a6ebdb/tp-monopoly/src/Lib.hs#L150

y no al jugador tal como _empezó_ a jugar

**Comment by natoszme** [comment]
Muy buenas abstracciones y delegaciones en general <3<3<3

**Comment by dlopezjoffreutn** [comment]
Gracias <3<3<3 Voy viendo de hacer las correcciones pertinentes durante el finde :)

**Comment by dlopezjoffreutn** [comment]
fixes en 44c8492
